### ISSUE TITLE
NullReferenceException if no path is given.

### ISSUE THREAD

**Issue by samvik** [brunurd/RTFExporter#2]
Hello,

If no path is set on the document using the parameter less constructor a NullReferenceException is thrown when dispose is called.

The following code reproduces the error.

var doc = new RTFDocument();
doc.Dispose();

A small feature request: It would be nice to be able to pass a Stream instead of a path to the document.

Thanks
/Björn

**Comment by leonaaraujo** [comment]
The constructor without parameter should not be a disposable, it's just a in memory object who can be converted to a string, I removed the null reference exception possibility and add new constructors with FileStream parameter in version 1.1.1.

**Comment by samvik** [comment]
Excellent, thanks.

The object is disposable (implements IDisposable) no matter what constructor you call. It's however ok if the dispose does nothing when the instance is constructed using that constructor.
