### ISSUE TITLE
You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework.

### ISSUE THREAD

**Issue by icnocop** [brunurd/RTFExporter#3]
Hi.

I tried to add the RTFExporter NuGet package to my project, but received the following error:

`Could not install package 'RTFExporter 1.1.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Visual Studio 2017
Class Library project targeting .NET Framework 4.6

I'm thinking README.md should be updated to indicate the project must target .NET Framework 4.6.1 or higher.

Thank you.

**Comment by leonaaraujo** [comment]
Added bagdes in README.md and in the nuget documentation. commit: 473948ee7cbc28dbae4f0df4872f54ab63403c37
